### ISSUE TITLE
Implant slice zoom window unresponsive 

### ISSUE THREAD

**Issue by kjy5** [VirtualBrainLab/NPTrajectoryPlanner#149] opened 2022-09-02 21:30 UTC
- Not zooming in or out
- Crashes when clicking regions

**Comment by dbirman** [comment] 2022-09-03 06:46
Can't reproduce in editor -- is this possibly an interaction between sensapex and the in-plane slice code?

**Comment by kjy5** [comment] 2022-09-03 06:49
I also was unable to reproduce this while i was still in the lab today with a 1.0 probe when i was connected with a manipulator. Could just be that build?

**Comment by dbirman** [comment] 2022-09-03 21:20
Reproduced this by re-scaling the UI canvas to weird sizes, appears to be related to the button moving to a weird position and possibly a transparency issue. I removed transparency from the parent object which appears to have fixed a bug where you could click "through" to a probe behind the zoom icons. 
Also fixed a bug where clicking on the active probe would call the `SetActiveProbe` function, creating unnecessary overhead and sometimes causing probes to jump position? 

Appears to be fixed for now.

**Closed by dbirman** 2022-09-03 21:20 UTC
Labels: bug
